baseURL = 'https://example.org/'
languageCode = 'zh-cn'
title = 'Styx Blog'
theme = 'Stack'

[Params]
	favicon = "mask.svg"
	description = "Styx Blog çƒ­çˆ±ç¼–ç¨‹ çƒ­çˆ±ç”Ÿæ´»"
	enableSearch = true
	mainSections = ["post"]

	[Params.Sidebar]
		emoji = "ğŸ§‘â€ğŸ’»"
		subtitle = "æ¬¢è¿æ¥åˆ°æˆ‘çš„åšå®¢"

		[Params.Sidebar.Avatar]
		src = "img/avatar.png"
		local = true
		enabled = true

	[Params.Article]
		toc = true
		readingTime = true

		[Params.Article.License]
			enabled = true

	[Params.Footer]
		since = 2025
		customText = """ """

[Menu]

	[[Menu.Social]]
		name = "GitHub"
		url = "https://github.com/OasisPioneer"
		identifier = "GitHub"
		[Menu.Social.Params]
			icon = "brand-github"
			newTab = true

	[[Menu.Social]]
		name = "Telegram"
		url = "https://t.me/StyxTechStudio"
		identifier = "Telegram"
		[Menu.Social.Params]
			icon = "brand-telegram"
			newTab = true

	[[Menu.Social]]
		name = "Sitemap"
		url = "/sitemap.xml"
		identifier = "Sitemap"
		[Menu.Social.Params]
			icon = "sitemap"
			newTab = true

	[[Menu.Social]]
		name = "Rss"
		url = "/index.xml"
		identifier = "Rss"
		[Menu.Social.Params]
			icon = "rss"
			newTab = true

	[[Menu.Main]]
		name = "é¦–é¡µ"
		url = "/"
		weight = 10
		identifier = "Home"
		[Menu.Main.Params]
			icon = "home"
			newTab = false

	[[Menu.Main]]
		name = "å½’æ¡£"
		url = "/archives/"
		weight = 20
		identifier = "Archive"
		[Menu.Main.Params]
			icon = "archives"
			newTab = false

	[[Menu.Main]]
		name = "åˆ†ç±»"
		url = "/categories/"
		weight = 30
		identifier = "Categories"
		[Menu.Main.Params]
			icon = "categories"
			newTab = false

	[[Menu.Main]]
		name = "æ ‡ç­¾"
		url = "/tags/"
		weight = 40
		identifier = "Label"
		[Menu.Main.Params]
			icon = "tag"
			newTab = false

	[[Menu.Main]]
		name = "å…³äº"
		url = "/about/"
		weight = 50
		identifier = "About"
		[Menu.Main.Params]
			icon = "user"
			newTab = false

	[[Menu.Main]]
		name = "æœç´¢"
		url = "/search/"
		weight = 60
		identifier = "Search"
		[Menu.Main.Params]
			icon = "search"
			newTab = false

[[Params.Widgets.Homepage]]
	type = "search"

[[Params.Widgets.Page]]
	type = "toc"

[[Params.Widgets.Homepage]]
	type = "archives"
	params.limit = 10

[[Params.Widgets.Homepage]]
	type = "categories"
	params.limit = 10

[[Params.Widgets.Homepage]]
	type = "tag-cloud"
	params.limit = 10

[Params.Comments]
	enabled = true
	provider = "giscus"
[Params.Comments.Giscus]
	repo = "OasisPioneer/OasisPioneer.GitHub.IO"
    repoID = "R_kgDOPcBVMQ"
    category="Announcements"
    categoryID="DIC_kwDOPcBVMc4CuCsc"
    mapping="pathname"
    strict = "0"
    lightTheme = "light"
    darkTheme = "dark"
    reactionsEnabled = "1"
    emitMetadata = "0"
    inputPosition = "top"
    lang = "zh-CN"